name: Check it's built
on:
  pull_request: {}

jobs: 
  check_built:
    name: Check dist directory is same as rebuilt one
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          # first, build
          node build/index.mjs
          # check it's built
          git diff --quiet HEAD || { echo "::error::it's not built" ; exit 1; }
